### ISSUE TITLE
"for more information" - mobile virsion

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#10]
On the mobile version, at the "הדוברות" part, when clicking - "למידע נוסף" nothing happen.
![image](https://cloud.githubusercontent.com/assets/26923359/26032418/12bd7b56-389c-11e7-8039-5955da94c4c1.png)

**Comment by MeanEYE** [comment]
Does something happen on desktop version?

**Comment by talovdat** [comment]
Yes. 
![image](https://cloud.githubusercontent.com/assets/26923359/26059696/52b4d39a-398b-11e7-9389-bb90c6e3bba0.png)
