### ISSUE TITLE
Backround sign color

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#11]
Need to change the color of the backround in the sign inside the heder.
File in Iliya's inbox.

**Comment by MeanEYE** [comment]
Screen shot of the sign in question would be welcome. Also, don't assume Iliya will do it.

**Comment by talovdat** [comment]
![image](https://cloud.githubusercontent.com/assets/26923359/26095860/deadff6a-3a27-11e7-934e-5b12166a918a.png)

**Comment by MeanEYE** [comment]
That's an image. Is the new design prepared?

**Comment by talovdat** [comment]
Yes, in Iliya's inbox. 
Sent it to you as well.

**Comment by MeanEYE** [comment]
Am assigning it to @VladimirWebDev.
