### ISSUE TITLE
Logo - header font

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#12]
Need to change the font of the logo in the hedder. 
Ready file in Iliya and Mladen's inbox

**Comment by MeanEYE** [comment]
Why are these changes coming now? Design was already approved.

**Comment by talovdat** [comment]
Font of the header in Google Drive in that address : 
https://drive.google.com/drive/u/0/folders/0B-UG-WNbNEVCTk5sZHVUUVdmT0U

File name : logo.svg
