### ISSUE TITLE
Change the header - new picture (jpg) 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#13]
File in Iliya and Mladen's inbox.

**Comment by MeanEYE** [comment]
Which file, which email?

**Comment by talovdat** [comment]
Due to stupidity, file in Google Drive in that address : 
https://drive.google.com/drive/u/0/folders/0B-UG-WNbNEVCTk5sZHVUUVdmT0U

file name : header-backround-03.jpg   .
