### ISSUE TITLE
Change the video title to "תמונות מהאירועים הקודמים" and remove the video. 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#14]
change the video section title to "תמונות מהאירועים הקודמים" and remove the video.

![default](https://cloud.githubusercontent.com/assets/26923359/26158053/666afa56-3b23-11e7-8986-be73d5b6d2c3.jpg)

**Comment by MeanEYE** [comment]
Issue here is of different kind. For some reason no one uploaded video, so title appears above video which is missing. @iliyaM is to add this missing video instead of changing the title.

**Comment by MeanEYE** [comment]
@talovdat make sure this is in lines with what client wants. If he wants video removed and this title changed, we can do that as well. I'd rather have site behave as originally planned and approved.

**Comment by talovdat** [comment]
Already talked with client. Change the video title and remove the video.
