### ISSUE TITLE
Center new logo.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#15]
Client has added new logo under article category "השותפים".
Align to center. 

![image](https://user-images.githubusercontent.com/26923359/27329017-bbf47606-55bc-11e7-9ce1-97f1c100fae0.png)

**Comment by VladimirWebDev** [comment]
@talovdat  Can I get DB-export for this site..?

**Comment by talovdat** [comment]
@eyalway2cu will provide.

**Comment by eyalway2cu** [comment]
@VladimirWebDev  please give me your email so I can send you the DB export.

**Comment by eyalway2cu** [comment]
@MeanEYE Needs to approve before I can send.

**Comment by VladimirWebDev** [comment]
vladimir@way2cu.com

**Comment by MeanEYE** [comment]
Make sure you don't export `system_*` tables. He doesn't need those and further more it's a security risk to thrown them around online.

**Comment by eyalway2cu** [comment]
Sent to @VladimirWebDev  without system_* tables

**Comment by VladimirWebDev** [comment]
@talovdat  Is that new logo somewhere on Drive. In IBI shik folder on Drive I only found that initial three.

**Comment by talovdat** [comment]
The new logo is already up there. Posted the image explaining the issue at
first comment.

בתאריך 20 ביוני 2017 18:56,‏ "VladimirWebDev" <notifications@github.com>
כתב:

**Comment by iliyaM** [comment]
@VladimirWebDev 
No need to DB just 'text-align: center' on 
section#about > article > div.images
:)

**Comment by VladimirWebDev** [comment]
Yes. I did that but wanted to see how page looks. Thanks anyway..

**Comment by iliyaM** [comment]
Sure. next time talk to me ill give everything you need

**Comment by VladimirWebDev** [comment]
Ok.. Thanks !
