### ISSUE TITLE
Dynamically space program entries

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#18]
When adding a new article to a 'Programs' group, the article goes over the existing ones.

**Comment by MeanEYE** [comment]
![image](https://user-images.githubusercontent.com/1911594/31767236-97bb2808-b4ca-11e7-8f67-9184df139ab6.png)
This is the thing he's talking about. Issue here is they need to be positioned equally along the line no matter the number of points. As they are right now they are positioned manually. To achieve automatic positioning either flexbox should be used or `display: table`.

**Comment by MeanEYE** [comment]
Domain is: http://hashik.co.il/
