### ISSUE TITLE
Time line 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Shik-Site#7]
![capture 5](https://cloud.githubusercontent.com/assets/26923359/25852160/13c86eda-34d1-11e7-94c4-fcb8f2d7efc5.PNG)
 Need to add 2 more dots of time line connected to the other.

**Comment by MeanEYE** [comment]
Am not sure there's enough space for this. @iliyaM can you check how @talrez11 did this one? I think it's absolutely positioned features but I am not sure.
